name: authenticate-docker-image-sbom
on:
  push:
    branches: [main]

jobs:
  authenticate-image-sbom:
    runs-on: ubuntu-latest
      # Pull an image whos SBOM has been previously notarized
      - name: debug
        run: docker pull codenotary/cas:bom-docker
        shell: bash

      - name: authenticate sample asset
        #--> Run the GitHub action
        uses: codenotary/cas-notarize-asset-github-action@main
        with:
          # Whatever asset is being notarized, can be a target/ or dist/ compiled binary or any type of file
          asset: docker://codenotary/cas:bom-docker
		  # Your signerID is the only thing needed to authenticate assets
		  # this can be done in both base64 or plaintext, and will be the email address used to generate your API Key
          signerID: Y29kZW5vdGFyeXRlc3QrMTNAZ21haWwuY29t

